[package]
name = "locator"
version = "0.1.0"
authors = ["Dave Yarwood <dave.yarwood@gmail.com>"]

[dependencies]
schemamama_rusqlite = "0.5.0"
schemamama          = "0.2.0"
rusqlite            = "0.6.0"
time                = "0.1.35"
zmq                 = "0.8"
